
// This header file is auto-generated from the file cosmosis/datablock/section_names.txt.
// Edit that and then re-make to add your own pre-defined section names.

#define LIKELIHOODS_SECTION "likelihoods"
#define DATA_VECTOR_SECTION "data_vector"
#define COSMOLOGICAL_PARAMETERS_SECTION "cosmological_parameters"
#define HALO_MODEL_PARAMETERS_SECTION "halo_model_parameters"
#define BARYON_PARAMETERS_SECTION "baryon_parameters"
#define GALCL_CALIBRATION_PARAMETERS_SECTION "galcl_calibration_parameters"
#define NUMBER_DENSITY_PARAMS_SECTION "number_density_params"
#define POST_FRIEDMANN_PARAMETERS_SECTION "post_friedmann_parameters"
#define INTRINSIC_ALIGNMENT_PARAMETERS_SECTION "intrinsic_alignment_parameters"
#define INTRINSIC_POWER_SECTION "intrinsic_power"
#define GALAXY_INTRINSIC_POWER_SECTION "galaxy_intrinsic_power"
#define MATTER_INTRINSIC_POWER_SECTION "matter_intrinsic_power"
#define WL_NUMBER_DENSITY_SECTION "wl_number_density"
#define MATTER_POWER_NL_SECTION "matter_power_nl"
#define MATTER_POWER_LIN_SECTION "matter_power_lin"
#define MATTER_GALAXY_POWER_SECTION "matter_galaxy_power"
#define GALAXY_POWER_SECTION "galaxy_power"
#define GALCL_XI_SECTION "galcl_xi"
#define GALCL_CL_SECTION "galcl_cl"
#define GALCL_CL_GG_SECTION "galcl_cl_gg"
#define GALCL_CL_GI_SECTION "galcl_cl_gi"
#define GALCL_CL_II_SECTION "galcl_cl_ii"
#define GALAXY_CL_SECTION "galaxy_cl"
#define CMB_CL_SECTION "cmb_cl"
#define LSS_AUTOCORRELATION_SECTION "lss_autocorrelation"
#define GAL_MATTER_POWER_LIN_SECTION "gal_matter_power_lin"
#define LINEAR_CDM_TRANSFER_SECTION "linear_cdm_transfer"
#define SIGMA_R_LIN_SECTION "sigma_r_lin"
#define SIGMA_R_NL_SECTION "sigma_r_nl"
#define GALAXY_XI_SECTION "galaxy_xi"
#define GALAXY_GALCL_XI_SECTION "galaxy_galcl_xi"
#define GALAXY_INTRINSIC_XI_SECTION "galaxy_intrinsic_xi"
#define PLANCK_SECTION "planck"
#define INTRINSIC_ALIGNMENT_FIELD_SECTION "intrinsic_alignment_field"
#define FGAS_PARAMETERS_SECTION "fgas_parameters"
#define GALCL_CALIBRATION_SECTION "galcl_calibration"
#define SUPERNOVA_PARAMS_SECTION "supernova_params"
#define BIAS_FIELD_SECTION "bias_field"
#define GALAXY_LUMINOSITY_FUNCTION_SECTION "galaxy_luminosity_function"
#define DISTANCES_SECTION "distances"
#define DE_EQUATION_OF_STATE_SECTION "de_equation_of_state"
#define GROWTH_PARAMETERS_SECTION "growth_parameters"
#define TEST_PARAMETERS_SECTION "test_parameters"
#define MASS_FUNCTION_SECTION "mass_function"
#define EVS_SECTION "evs"
#define CLUSTERS_SECTION "clusters"

