include ${COSMOSIS_SRC_DIR}/config/compilers.mk
include ${COSMOSIS_SRC_DIR}/config/subdirs.mk

#SUBDIRS = boltzmann shear supernovae structure mass_function likelihood
SUBDIRS = boltzmann supernovae structure mass_function likelihood
