#! /usr/bin/env python
# don't do much for now
from optparse import OptionParser
parser = OptionParser()

parser.add_option("--cflags", action="store_true",
                  help="only the cflags")
parser.add_option("--libs", action="store_true",
                  help="only libflags")

(options, args) = parser.parse_args()


res={}
cflags = """-m64  -fPIC  -D HAS_LAPACK -D LAPACK_CLIK -D NOHEALPIX -D CLIK_LENSING -D 'CLIKSVNVERSION="5887 MAKEFILE"' -J /home/ktanidis/cosmosis/cosmosis-standard-library/likelihood/planck/plc-1.0/include"""
libs = """-m64 -L/usr1/local/lib -lcfitsio -lgfortran  -ldl -lm -lpthread -L/usr1/local/lib -lcfitsio -lgfortran   -L/path/to/lapack/lib -llapack -lblas -L/home/ktanidis/cosmosis/cosmosis-standard-library/likelihood/planck/plc-1.0/lib -lclik -lclik_f90"""

if (not options.libs) and (not options.cflags):
  options.libs=True
  options.cflags=True

if options.cflags:
  print cflags,
if options.libs:
  print libs,
print


